# Generated by Django 5.0.2 on 2024-02-19 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCIChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField()),
                ('weight', models.IntegerField(default=1, help_text='The importance of the item')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Checklist Items',
                'ordering': ['requirement', 'item_description'],
            },
        ),
        migrations.CreateModel(
            name='PCIRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_number', models.CharField(max_length=10)),
                ('requirement_description', models.TextField()),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'PCI Requirements',
                'ordering': ['standard', 'requirement_number'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=100)),
                ('standard_organization', models.CharField(max_length=100)),
                ('standard_description', models.TextField()),
                ('standard_source', models.URLField()),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Standards',
                'ordering': ['standard_name'],
            },
        ),
        migrations.CreateModel(
            name='PCIChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compliance_checker.pcichecklistitem')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pci_responses', to='compliance_checker.pcirequirement')),
            ],
            options={
                'verbose_name_plural': 'Checklist Responses',
                'ordering': ['checklist_item'],
            },
        ),
        migrations.AddField(
            model_name='pcichecklistitem',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pci_items', to='compliance_checker.pcirequirement'),
        ),
        migrations.AddField(
            model_name='pcirequirement',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pci_requirements', to='compliance_checker.standard'),
        ),
    ]
