# Generated by Django 5.0.2 on 2024-02-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcichecklistitem',
            options={'ordering': ['requirement', 'item_description'], 'verbose_name_plural': 'PCI Checklist Items'},
        ),
        migrations.AddField(
            model_name='standard',
            name='standard_abbreviation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
