# Generated by Django 5.0.2 on 2024-02-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0002_alter_pcichecklistitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcichecklistitem',
            old_name='weight',
            new_name='checklist_number',
        ),
    ]
