# Generated by Django 5.0.2 on 2024-02-19 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0003_rename_weight_pcichecklistitem_checklist_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIPAAChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField()),
                ('checklist_number', models.IntegerField(default=1, help_text='The importance of the item')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'HIPAA Checklist Items',
                'ordering': ['rule', 'item_description'],
            },
        ),
        migrations.AlterField(
            model_name='pcichecklistresponse',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_checker.pcichecklistitem'),
        ),
        migrations.CreateModel(
            name='HIPAARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_number', models.CharField(max_length=10)),
                ('rule_description', models.TextField()),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipaa_rules', to='compliance_checker.standard')),
            ],
            options={
                'verbose_name_plural': 'HIPAA Rules',
                'ordering': ['standard', 'rule_number'],
            },
        ),
        migrations.CreateModel(
            name='HIPAAChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_checker.hipaachecklistitem')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hipaa_responses', to='compliance_checker.hipaarule')),
            ],
            options={
                'verbose_name_plural': 'HIPAA Checklist Responses',
                'ordering': ['checklist_item'],
            },
        ),
        migrations.AddField(
            model_name='hipaachecklistitem',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipaa_items', to='compliance_checker.hipaarule'),
        ),
    ]
