# Generated by Django 5.0.2 on 2024-02-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0004_hipaachecklistitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hipaarule',
            old_name='rule_description',
            new_name='rule_title',
        ),
    ]
