# Generated by Django 5.0.2 on 2024-02-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0006_rename_hipaarule_hipaarequirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hipaarequirement',
            options={'ordering': ['standard', 'requirement_number'], 'verbose_name_plural': 'HIPAA Requirements'},
        ),
        migrations.RenameField(
            model_name='hipaarequirement',
            old_name='rule_number',
            new_name='requirement_number',
        ),
    ]
