# Generated by Django 5.0.2 on 2024-02-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0007_alter_hipaarequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipaarequirement',
            name='requirement_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
