# Generated by Django 5.0.2 on 2024-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0011_remove_hipaachecklistitem_checklist_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipaachecklistitem',
            name='item_description',
            field=models.CharField(max_length=255),
        ),
    ]
