# Generated by Django 5.0.2 on 2024-02-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0013_iso27001checklistitem_iso27001controlgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iso27001checklistitem',
            name='item_description',
            field=models.CharField(max_length=255),
        ),
    ]
