# Generated by Django 5.0.2 on 2024-02-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0014_alter_iso27001checklistitem_item_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iso27001controlgroup',
            options={'ordering': ['control_group_number'], 'verbose_name_plural': 'ISO27001 Control Groups'},
        ),
    ]
