# Generated by Django 5.0.2 on 2024-02-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0015_alter_iso27001controlgroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcichecklistitem',
            options={'ordering': ['requirement', 'checklist_number'], 'verbose_name_plural': 'PCI Checklist Items'},
        ),
        migrations.AlterField(
            model_name='pcirequirement',
            name='requirement_number',
            field=models.IntegerField(),
        ),
    ]
