# Generated by Django 5.0.2 on 2024-02-19 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0016_alter_pcichecklistitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcichecklistresponse',
            options={'ordering': ['checklist_item'], 'verbose_name': 'PCI Checklist Response', 'verbose_name_plural': 'PCI Checklist Responses'},
        ),
        migrations.AddField(
            model_name='hipaachecklistresponse',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hipaa_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iso27001checklistresponse',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iso_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcichecklistresponse',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pci_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
