# Generated by Django 5.0.2 on 2024-02-19 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0018_rename_rule_title_hipaarequirement_requirement_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hipaachecklistitem',
            options={'ordering': ['requirement', 'item_description'], 'verbose_name_plural': 'HIPAA Checklist Items'},
        ),
        migrations.RenameField(
            model_name='hipaachecklistitem',
            old_name='rule',
            new_name='requirement',
        ),
        migrations.RenameField(
            model_name='hipaachecklistresponse',
            old_name='rule',
            new_name='requirement',
        ),
        migrations.AlterField(
            model_name='hipaarequirement',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipaa_requirements', to='compliance_checker.standard'),
        ),
    ]
