# Generated by Django 5.0.2 on 2024-02-19 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0019_alter_hipaachecklistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iso27001checklistitem',
            name='control_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso27k_items', to='compliance_checker.iso27001controlgroup'),
        ),
    ]
