# Generated by Django 5.0.2 on 2024-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(help_text='Enter your business name as per the registration certificate', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_phone',
            field=models.CharField(help_text='Enter your business phone number', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_website',
            field=models.URLField(help_text='Enter the URL of your business website i.e. https://www.example.com', max_length=100),
        ),
    ]
