# Generated by Django 5.0.2 on 2024-02-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_business_business_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['business_name'], 'verbose_name_plural': 'Businesses'},
        ),
    ]
